// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/tableMasterData.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/algolia.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/brand-assistant.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$4 from "./apps/deco/implementation.ts";
import * as $$$$$$$$$$$5 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$6 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$7 from "./apps/deco/weather.ts";
import * as $$$$$$$$$$$8 from "./apps/deco/workflows.ts";
import * as $$$$$$$$$$$9 from "./apps/decohub.ts";
import * as $$$$$$$$$$$10 from "./apps/site.ts";
import * as $$$2 from "./loaders/availableIcons.ts";
import * as $$$3 from "./loaders/icons.ts";
import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$4 from "./loaders/sidebarMenu.ts";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Brands.tsx";
import * as $$$$$$2 from "./sections/BuildYourBusiness/BusinessBanner.tsx";
import * as $$$$$$3 from "./sections/BuildYourBusiness/BusinessBreadCrumb.tsx";
import * as $$$$$$4 from "./sections/BuildYourBusiness/BusinessBuilder.tsx";
import * as $$$$$$5 from "./sections/BuildYourBusiness/BusinessCards.tsx";
import * as $$$$$$6 from "./sections/BuildYourBusiness/BusinessGoBackLink.tsx";
import * as $$$$$$7 from "./sections/BuildYourBusiness/BusinessProductCard.tsx";
import * as $$$$$$8 from "./sections/Cards/IconCardsCarousel.tsx";
import * as $$$$$$9 from "./sections/Cards/IconCardsCarouselWithImage.tsx";
import * as $$$$$$10 from "./sections/Cards/ImageCardsCarousel.tsx";
import * as $$$$$$11 from "./sections/Cards/ImageCardsCarouselWithImage.tsx";
import * as $$$$$$13 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$14 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$15 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$12 from "./sections/CategoryList.tsx";
import * as $$$$$$16 from "./sections/ChoiceUltrafeu.tsx";
import * as $$$$$$17 from "./sections/Content/Benefits.tsx";
import * as $$$$$$18 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$19 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$20 from "./sections/Content/Faq.tsx";
import * as $$$$$$21 from "./sections/Content/Features.tsx";
import * as $$$$$$22 from "./sections/Content/Hero.tsx";
import * as $$$$$$23 from "./sections/Content/ImageSection.tsx";
import * as $$$$$$24 from "./sections/Content/Intro.tsx";
import * as $$$$$$25 from "./sections/Content/Logos.tsx";
import * as $$$$$$26 from "./sections/Content/Partners.tsx";
import * as $$$$$$27 from "./sections/Content/RichText.tsx";
import * as $$$$$$28 from "./sections/Content/Table.tsx";
import * as $$$$$$29 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$30 from "./sections/Content/TextWithImage.tsx";
import * as $$$$$$31 from "./sections/FloatCards.tsx";
import * as $$$$$$32 from "./sections/Footer.tsx";
import * as $$$$$$33 from "./sections/Footer/Footer.tsx";
import * as $$$$$$34 from "./sections/Gallery.tsx";
import * as $$$$$$35 from "./sections/Header/Header.tsx";
import * as $$$$$$36 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$37 from "./sections/Images/Carousel.tsx";
import * as $$$$$$38 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$39 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$40 from "./sections/Institutional/InstitutionalAboutUs.tsx";
import * as $$$$$$41 from "./sections/Institutional/InstitutionalContactForm.tsx";
import * as $$$$$$42 from "./sections/Institutional/InstitutionalWithSidebar.tsx";
import * as $$$$$$43 from "./sections/Institutional/InstitutionalWorkWithUsForm.tsx";
import * as $$$$$$44 from "./sections/Institutional/SidebarMenuMobile.tsx";
import * as $$$$$$45 from "./sections/ItWorks.tsx";
import * as $$$$$$46 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$47 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$48 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$49 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$50 from "./sections/Miscellaneous/Slide.tsx";
import * as $$$$$$51 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$52 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$53 from "./sections/Product/NotFound.tsx";
import * as $$$$$$54 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$55 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$56 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$57 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$58 from "./sections/Product/PromotionProductCardInHighLight.tsx";
import * as $$$$$$59 from "./sections/Product/PromotionProducts.tsx";
import * as $$$$$$60 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$61 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$62 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$63 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$64 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$65 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/availableIcons.ts": $$$2,
    "site/loaders/icons.ts": $$$3,
    "site/loaders/Layouts/ProductCard.tsx": $$$0,
    "site/loaders/List/Sections.tsx": $$$1,
    "site/loaders/sidebarMenu.ts": $$$4,
  },
  "sections": {
    "site/sections/Animation/Animation.tsx": $$$$$$0,
    "site/sections/Brands.tsx": $$$$$$1,
    "site/sections/BuildYourBusiness/BusinessBanner.tsx": $$$$$$2,
    "site/sections/BuildYourBusiness/BusinessBreadCrumb.tsx": $$$$$$3,
    "site/sections/BuildYourBusiness/BusinessBuilder.tsx": $$$$$$4,
    "site/sections/BuildYourBusiness/BusinessCards.tsx": $$$$$$5,
    "site/sections/BuildYourBusiness/BusinessGoBackLink.tsx": $$$$$$6,
    "site/sections/BuildYourBusiness/BusinessProductCard.tsx": $$$$$$7,
    "site/sections/Cards/IconCardsCarousel.tsx": $$$$$$8,
    "site/sections/Cards/IconCardsCarouselWithImage.tsx": $$$$$$9,
    "site/sections/Cards/ImageCardsCarousel.tsx": $$$$$$10,
    "site/sections/Cards/ImageCardsCarouselWithImage.tsx": $$$$$$11,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$13,
    "site/sections/Category/CategoryGrid.tsx": $$$$$$14,
    "site/sections/Category/CategoryList.tsx": $$$$$$15,
    "site/sections/CategoryList.tsx": $$$$$$12,
    "site/sections/ChoiceUltrafeu.tsx": $$$$$$16,
    "site/sections/Content/Benefits.tsx": $$$$$$17,
    "site/sections/Content/BlogPosts.tsx": $$$$$$18,
    "site/sections/Content/CallToAction.tsx": $$$$$$19,
    "site/sections/Content/Faq.tsx": $$$$$$20,
    "site/sections/Content/Features.tsx": $$$$$$21,
    "site/sections/Content/Hero.tsx": $$$$$$22,
    "site/sections/Content/ImageSection.tsx": $$$$$$23,
    "site/sections/Content/Intro.tsx": $$$$$$24,
    "site/sections/Content/Logos.tsx": $$$$$$25,
    "site/sections/Content/Partners.tsx": $$$$$$26,
    "site/sections/Content/RichText.tsx": $$$$$$27,
    "site/sections/Content/Table.tsx": $$$$$$28,
    "site/sections/Content/Testimonials.tsx": $$$$$$29,
    "site/sections/Content/TextWithImage.tsx": $$$$$$30,
    "site/sections/FloatCards.tsx": $$$$$$31,
    "site/sections/Footer.tsx": $$$$$$32,
    "site/sections/Footer/Footer.tsx": $$$$$$33,
    "site/sections/Gallery.tsx": $$$$$$34,
    "site/sections/Header/Header.tsx": $$$$$$35,
    "site/sections/Images/BannerGrid.tsx": $$$$$$36,
    "site/sections/Images/Carousel.tsx": $$$$$$37,
    "site/sections/Images/ImageGallery.tsx": $$$$$$38,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$39,
    "site/sections/Institutional/InstitutionalAboutUs.tsx": $$$$$$40,
    "site/sections/Institutional/InstitutionalContactForm.tsx": $$$$$$41,
    "site/sections/Institutional/InstitutionalWithSidebar.tsx": $$$$$$42,
    "site/sections/Institutional/InstitutionalWorkWithUsForm.tsx": $$$$$$43,
    "site/sections/Institutional/SidebarMenuMobile.tsx": $$$$$$44,
    "site/sections/ItWorks.tsx": $$$$$$45,
    "site/sections/Links/LinkTree.tsx": $$$$$$46,
    "site/sections/Links/Shortcuts.tsx": $$$$$$47,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$48,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$49,
    "site/sections/Miscellaneous/Slide.tsx": $$$$$$50,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$51,
    "site/sections/Product/ImageGalleryFrontBack.tsx": $$$$$$52,
    "site/sections/Product/NotFound.tsx": $$$$$$53,
    "site/sections/Product/NotFoundChallenge.tsx": $$$$$$54,
    "site/sections/Product/ProductDetails.tsx": $$$$$$55,
    "site/sections/Product/ProductShelf.tsx": $$$$$$56,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$57,
    "site/sections/Product/PromotionProductCardInHighLight.tsx": $$$$$$58,
    "site/sections/Product/PromotionProducts.tsx": $$$$$$59,
    "site/sections/Product/SearchResult.tsx": $$$$$$60,
    "site/sections/Product/ShelfWithImage.tsx": $$$$$$61,
    "site/sections/Product/Wishlist.tsx": $$$$$$62,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$63,
    "site/sections/Social/WhatsApp.tsx": $$$$$$64,
    "site/sections/Theme/Theme.tsx": $$$$$$65,
  },
  "actions": {
    "site/actions/tableMasterData.ts": $$$$$$$$$0,
  },
  "apps": {
    "site/apps/deco/algolia.ts": $$$$$$$$$$$0,
    "site/apps/deco/analytics.ts": $$$$$$$$$$$1,
    "site/apps/deco/brand-assistant.ts": $$$$$$$$$$$2,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$3,
    "site/apps/deco/implementation.ts": $$$$$$$$$$$4,
    "site/apps/deco/records.ts": $$$$$$$$$$$5,
    "site/apps/deco/vtex.ts": $$$$$$$$$$$6,
    "site/apps/deco/weather.ts": $$$$$$$$$$$7,
    "site/apps/deco/workflows.ts": $$$$$$$$$$$8,
    "site/apps/decohub.ts": $$$$$$$$$$$9,
    "site/apps/site.ts": $$$$$$$$$$$10,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
